//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedules
    {
        public int ScheduleID { get; set; }
        public int EmployeeID { get; set; }
        public int DayOfWeek { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public bool IsWorkingDay { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
